routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function () {

    Auth::routes(['register' => false]);
});
//
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Auth::routes(['register' => false]);

Route::get('/dashboard', 'App\Http\Controllers\HomeController@index')->name('dashboard')->middleware('auth');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::resource('Invited', 'App\Http\Controllers\InvitedController');
    Route::resource('clients', 'App\Http\Controllers\ClientController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
});

Route::prefix(LaravelLocalization::setLocale())->middleware([
    'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'])
    ->group(function () {

    Route::get('/', [App\Http\Controllers\ClientController::class, 'register'])->name('home');

    Route::post('save_data', [App\Http\Controllers\ClientController::class, 'save_data'])->name('save_data');

    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

/**
 * Class User
 * @mixin Builder
 * @package App\Models
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    protected $guarded = ['id'];

    protected $hidden = [
        'password',
        'remember_token',
    ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function something(){
        return $this->hasOne(User::class , 'id');
    }

    public function setPasswordAttribute($pass){
        $this->attributes['password'] = Hash::make($pass);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Enums\RoleEnum;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param Request $request
     * @param DataTables $dataTables
     * @return JsonResponse|Application|Factory|View
     * @throws Exception
     */
    public function index(Request $request , DataTables $dataTables){
        $items = User::with(['something'])->select('users.*');
        if($request->ajax()){
            return $dataTables->eloquent($items)
                ->addColumn('action', function ($item) {
                return '
                        <div style="white-space: nowrap;" class="td-actions text-right">
                            <a class="edit btn btn-xs btn-primary" style="color:#fff" href="'.route('user.edit',$item->id).'" ><i class="fa fa-edit"></i></a>
                            <a class="delete btn btn-xs btn-dark" style="color:#fff"><i class="fa fa-trash"></i></a>
                        </div>';
                })
                ->make(true);
        }
        return view('users.index');
    }

    public function create(){
        $roles = Role::all();
        return view('users.create',compact('roles'));
    }

    public function store(Request $request){
        $validated = $request->validate([
            'first_name' => ['required', 'min:3','string'],
            'last_name' => ['required', 'min:3','string'],
            'email' => ['required', 'email', 'unique:users,email'],
            'password' => ['required','confirmed','min:8'],
            'role' => ['required','string', Rule::in([RoleEnum::ADMIN])],
        ]);
        $role = $validated['role'];
        unset($validated['role']);

        $user = User::create($validated);
        $user->assignRole($role);

        return redirect()->route('user.index')->with('success','User Added Successfully');
    }

    public function update(Request $request,$id){
        $validated = $request->validate([
            'first_name' => ['required', 'min:3','string'],
            'last_name' => ['required', 'min:3','string'],
            'email' => ['required', 'email', 'unique:users,email,'.$id],
            'password' => ['nullable','confirmed','min:8'],
            'role' => ['required','string', Rule::in([RoleEnum::ADMIN])],
        ]);

        $role = $validated['role'];
        unset($validated['role']);

        $model = User::findOrFail($id);
        $model->update($validated);
        $model->assignRole($role);

        return redirect()->route('user.index')->with('success','User Updated Successfully');
    }

    public function edit($id){
        $model = User::findOrFail($id);
        $roles = Role::all();
        $user_role = optional($model->roles()->first())->name;
        return view('users.edit',compact('model','roles','user_role'));
    }

    public function destroy($id){
        $model = User::findOrFail($id);
        $model->delete();
        return response()->json(['message' => 'Successfully Deleted!']);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app', ['activePage' => 'admin-management', 'titlePage' => __('Admin Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Admin</h4>
                            <p class="card-category"> add new admin</p>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{route('user.store')}}">
                                @csrf
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="first_name">First Name</label>
                                        <input type="text" class="form-control" name="first_name" id="first_name" required placeholder="First Name ..." value="{{old('first_name')}}">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="last_name">Last Name</label>
                                        <input type="text" class="form-control" name="last_name" id="last_name" required placeholder="Last Name ..." value="{{old('last_name')}}">
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" name="email" id="email" required placeholder="Email ..." value="{{old('email')}}">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="password">Password</label>
                                        <input type="password" min="8" class="form-control" name="password" id="password" placeholder="********">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="password_confirmation">Confirm Password</label>
                                        <input type="password" min="8" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="********">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="role">Role</label>
                                        <select class="form-control selectpicker" name="role" required>
                                            <option selected disabled>Select a Role</option>
                                            @foreach($roles as $role)
                                                <option value="{{$role->name}}" @if(old('role') == $role->name) selected @endif>{{$role->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary float-right">Create</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')

@endpush

resources/views/users/edit.blade.php
@extends('layouts.app', ['activePage' => 'admin-management', 'titlePage' => __('Admin Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Admin</h4>
                            <p class="card-category"> edit admin</p>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{route('user.update',$model->id)}}">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="first_name">First Name</label>
                                        <input type="text" class="form-control" name="first_name" id="first_name" required value="{{old("first_name")??$model->first_name}}" placeholder="First Name ...">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="last_name">Last Name</label>
                                        <input type="text" class="form-control" name="last_name" id="last_name" required value="{{old("last_name")??$model->last_name}}" placeholder="Last Name ...">
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" name="email" id="email" required value="{{old("email")??$model->email}}" placeholder="Email ...">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="password">Password</label>
                                        <input type="password" min="8" class="form-control" name="password" id="password" placeholder="********">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="password_confirmation">Confirm Password</label>
                                        <input type="password" min="8" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="********">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="role">Role</label>
                                        <select class="form-control selectpicker" name="role" required>
                                            <option selected disabled>Select a Role</option>
                                            @foreach($roles as $role)
                                                <option @if($user_role == $role->name || old("role") == $role->name) selected @endif value="{{$role->name}}">{{$role->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary float-right">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')

@endpush

resources/views/users/index.blade.php
@extends('layouts.app', ['activePage' => 'admin-management', 'titlePage' => __('Admin Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{$message}}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Admin</h4>
                            <p class="card-category"> Here you can manage admins</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{route('user.create')}}" class="btn btn-sm btn-primary">Add Admin</a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table" id="main-table">
                                    <thead class="text-primary">
                                    <tr>
                                        <th>ID</th>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Email</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        var table;
        $(function () {
            table = $('#main-table').DataTable({
                fixedHeader:true,
                processing: true,
                serverSide: true,
                lengthMenu : [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                ajax: '{!! route('user.index') !!}',
                dom: 'QBlfrtip',
                buttons: [

                ],
                columns: [
                    {"data": "id"},
                    {"data": "first_name"},
                    {"data": "last_name"},
                    {"data": "email"},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            });
            table.on('click', '.delete', function () {
                $tr = $(this).closest('tr');
                if ($($tr).hasClass('child')) {
                    $tr = $tr.prev('.parent')
                }
                var data = table.row($tr).data();
                deleteOpr(data.id, `admin/user/` + data.id, table);
            });
        });
    </script>
@endpush