routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function () {

    Auth::routes(['register' => false]);
});
//
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Auth::routes(['register' => false]);

Route::get('/dashboard', 'App\Http\Controllers\HomeController@index')->name('dashboard')->middleware('auth');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::resource('Invited', 'App\Http\Controllers\InvitedController');
    Route::resource('clients', 'App\Http\Controllers\ClientController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
});

Route::prefix(LaravelLocalization::setLocale())->middleware([
    'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'])
    ->group(function () {

    Route::get('/', [App\Http\Controllers\ClientController::class, 'register'])->name('home');

    Route::post('save_data', [App\Http\Controllers\ClientController::class, 'save_data'])->name('save_data');

    });

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white"
     data-image="{{ asset('material') }}/img/sidebar-1.jpg">
    <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
    <div class="logo">
        <a href="{{route('dashboard')}}" class="simple-text logo-normal">
            Task
            <br>
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('dashboard') }}">
                    <i class="material-icons">dashboard</i>
                    <p>{{ __('Dashboard') }}</p>
                </a>
            </li>
            <ul class="nav">
                <li class="nav-item{{ $activePage == 'admin-management' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('user.index') }}">
{{--                        <span class="sidebar-mini"> UM </span>--}}
                        <span class="sidebar-normal"> {{ __('Admin Management') }} </span>
                    </a>
                </li>
            </ul>
            <ul class="nav">
                <li class="nav-item{{ $activePage == 'Invited-people-management' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('Invited.index') }}">
{{--                        <span class="sidebar-mini"> CM </span>--}}
                        <span class="sidebar-normal"> {{ __('Invited People Management') }} </span>
                    </a>
                </li>
            </ul>
            <ul class="nav">
                <li class="nav-item{{ $activePage == 'Registered-people-management' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('clients.index') }}">
{{--                        <span class="sidebar-mini"> AM </span>--}}
                        <span class="sidebar-normal"> {{ __('Registered People Management') }} </span>
                    </a>
                </li>
            </ul>


        </ul>
    </div>
</div>