routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function () {

    Auth::routes(['register' => false]);
});
//
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Auth::routes(['register' => false]);

Route::get('/dashboard', 'App\Http\Controllers\HomeController@index')->name('dashboard')->middleware('auth');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::resource('Invited', 'App\Http\Controllers\InvitedController');
    Route::resource('clients', 'App\Http\Controllers\ClientController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
});

Route::prefix(LaravelLocalization::setLocale())->middleware([
    'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'])
    ->group(function () {

    Route::get('/', [App\Http\Controllers\ClientController::class, 'register'])->name('home');

    Route::post('save_data', [App\Http\Controllers\ClientController::class, 'save_data'])->name('save_data');

    });

app/Models/Invited.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invited extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $casts = [
        'created_at' => 'datetime:Y-m-d / H:i',
        'registered_at' => 'datetime:Y-m-d / H:i',
    ];
}

app/Http/Controllers/InvitedController.php
<?php

namespace App\Http\Controllers;

use App\Models\Invited;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class InvitedController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , DataTables $dataTables){
        $items = Invited::select('inviteds.*');

        if($request->ajax()){
            return $dataTables->eloquent($items)
                ->addColumn('action', function ($item) {

                    return '
                            <div style="white-space: nowrap;" class="td-actions text-right">
                                <a class="edit btn btn-xs btn-primary" style="color:#fff" href="'.route('Invited.edit',$item->id).'" ><i class="fa fa-edit"></i></a>
                                <a class="delete btn btn-xs btn-dark" style="color:#fff"><i class="fa fa-trash"></i></a>
                            </div>';
                })
                ->make(true);
        }
        return view('Invited.index');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        return view('Invited.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $model = Invited::create($request->all());
        return redirect()->route('Invited.index')->with('success','Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Invited  $invited
     * @return \Illuminate\Http\Response
     */
    public function show(Invited $invited)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Invited  $invited
     * @return \Illuminate\Http\Response
     */
    public function edit($id){
        $model = Invited::findOrFail($id);
        return view('Invited.edit',compact(['model']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Invited  $invited
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id){
        $model = Invited::findOrFail($id);
        $model->update($request->all());
        return redirect()->route('Invited.index')->with('success','Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Invited  $invited
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
        $model = Invited::findOrFail($id);;
        $model->delete();
        return response()->json(['message' => 'Successfully Deleted!']);
    }
}

resources/views/Invited/create.blade.php
@extends('layouts.app', ['activePage' => 'Invited-people-management', 'titlePage' => __('Invited People Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Invited People</h4>
                            <p class="card-category">add new data</p>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{route('Invited.store')}}">
                                @csrf
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="email">E-mail Of Person</label>
                                        <input type="email" class="form-control" name="email" id="email">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary float-right">Create</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')

@endpush

resources/views/Invited/edit.blade.php
@extends('layouts.app', ['activePage' => 'Invited-people-management', 'titlePage' => __('Invited People Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Invited People</h4>
                            <p class="card-category"> Edit Data</p>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{route('Invited.update',$model->id)}}">
                                @csrf
                                @method('PUT')
                                <div class="row">

                                    <div class="form-group col-md-6">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" name="email" id="email" required value="{{$model->email}}" placeholder="Email ...">
                                    </div>

                                </div>
                                <button type="submit" class="btn btn-primary float-right">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')

@endpush

resources/views/Invited/index.blade.php
@extends('layouts.app', ['activePage' => 'Invited-people-management', 'titlePage' => __('Invited People Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{$message}}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Invited People</h4>
                            <p class="card-category"> Here you can manage Data</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{route('Invited.create')}}" class="btn btn-sm btn-primary">Add invited person mail</a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table" id="main-table">
                                    <thead class="text-primary">
                                    <tr>

                                        <th>Client Email</th>
                                        <th>Registration at</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        var table;
        $(function () {
            table = $('#main-table').DataTable({
                fixedHeader:true,
                processing: true,
                serverSide: true,
                colReorder: true,
                // scrollX: true,
                lengthMenu : [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                ajax: '{!! route('Invited.index') !!}',
                dom: 'QBlfrtip',
                buttons: [
                ],
                columns: [

                    {"data": "email"},

                    {"data": "registered_at"},

                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            });
            table.on('click', '.delete', function () {
                $tr = $(this).closest('tr');
                if ($($tr).hasClass('child')) {
                    $tr = $tr.prev('.parent')
                }
                var data = table.row($tr).data();
                deleteOpr(data.id, `admin/Invited/` + data.id, table);
            });
        });
    </script>
@endpush