routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function () {

    Auth::routes(['register' => false]);
});
//
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Auth::routes(['register' => false]);

Route::get('/dashboard', 'App\Http\Controllers\HomeController@index')->name('dashboard')->middleware('auth');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::resource('Invited', 'App\Http\Controllers\InvitedController');
    Route::resource('clients', 'App\Http\Controllers\ClientController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
});

Route::prefix(LaravelLocalization::setLocale())->middleware([
    'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'])
    ->group(function () {

    Route::get('/', [App\Http\Controllers\ClientController::class, 'register'])->name('home');

    Route::post('save_data', [App\Http\Controllers\ClientController::class, 'save_data'])->name('save_data');

    });

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

/**
 * Class Client
 * @mixin Builder
 * @package App\Models
 */
class Client extends Model
{
    use HasFactory,Notifiable;

    protected $guarded = ['id'];
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i',
    ];

    public function data_forms(){
        return $this->hasOne(DataForm::class,'client_id');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Enums\RoleEnum;

use App\Models\Client;

use App\Models\Invited;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Yajra\DataTables\DataTables;

class ClientController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param Request $request
     * @param DataTables $dataTables
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|JsonResponse
     * @throws \Exception
     */
    public function index(Request $request , DataTables $dataTables){
        $items = Client::select('clients.*');

        if($request->ajax()){
            return $dataTables->eloquent($items)
                ->addColumn('action', function ($item) {

                    return '
                            <div style="white-space: nowrap;" class="td-actions text-right">
                                <a class="btn btn-xs btn-warning" title="download Qrcode" style="color:#fff" download  href="'. asset('/'.$item->qrcode) .'"><i class="fa fa-qrcode"></i></a>
                                <a class="edit btn btn-xs btn-primary" style="color:#fff" href="'.route('clients.edit',$item->id).'" ><i class="fa fa-edit"></i></a>
                                <a class="delete btn btn-xs btn-dark" style="color:#fff"><i class="fa fa-trash"></i></a>
                            </div>';
                })
                ->make(true);
        }
        return view('client.index');
    }

    public function create(){
        return view('client.create');
    }

    public function store(Request $request){
        $model = Client::create($request->all());
        return redirect()->route('clients.index')->with('success','Added Successfully');
    }

//    public function show($data_form_id){
//        $model = DataForm::with(['client'])->find($data_form_id);
//        $client = $model->client;
//        return view('clients.show',compact(['model','client']));
//    }

    public function register(){
        return view('front.index');
    }
    public function save_data(Request $request){
        $validated =$request->validate([
            'first_name' => ['required', 'string', 'max:45'],
            'last_name'  => ['required', 'string', 'max:45'],
            'email'      => ['required', 'string', 'email', 'max:45'],
            'telephone'  => ['required', 'string', 'max:45'],
            'position'   => ['required', 'string', 'max:45'],
            'side'       => ['required', 'string', 'max:45'],
            'message'    => ['required', 'string'],
        ]);

        $invitation = Invited::where('email',$validated['email'])->first();
        $message = "You Have Been Registered";
        if($invitation){
            $invitation->registered_at = $invitation->registered_at ?? now();
            $invitation->save();
            $message = "Your Invitation has been Confirmed!";
        }

        $old_client = Client::where('email',$validated['email'])->first();

        $random_str = Uuid::uuid4()->toString();

        QrCode::size(400)->generate($random_str , public_path('img/qr/'.$random_str . '.svg'));

        $seat_number = sprintf('%08d', rand(111111,999999));
        do{
            $seat_number = sprintf('%08d', rand(111111,999999));
        }while(Client::where('seat_number',$seat_number)->count() > 0);

        if($old_client){
            $old_client->update($validated + ['qrcode' => 'img/qr/'.$random_str . '.svg','seat_number'=>$seat_number]);
        } else {
            $client = Client::create($validated + ['qrcode' => 'img/qr/'.$random_str . '.svg','seat_number'=>$seat_number]);
        }


        return response()->json(["message" => $message]);
    }

    public function update(Request $request,$id){
        $model = Client::findOrFail($id);
        $model->update($request->all());
        return redirect()->route('clients.index')->with('success','Updated Successfully');
    }

    public function edit($id){
        $model = Client::findOrFail($id);
        return view('client.edit',compact(['model']));
    }

    public function destroy($id){
        $model = Client::findOrFail($id);;
        $model->delete();
        return response()->json(['message' => 'Successfully Deleted!']);
    }


}

resources/views/client/edit.blade.php
@extends('layouts.app', ['activePage' => 'Registered-people-management', 'titlePage' => __('Registered People Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Registered Person</h4>
                            <p class="card-category"> edit data</p>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{route('clients.update',$model->id)}}">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label for="first_name">First Name</label>
                                        <input type="text" class="form-control" name="first_name" id="first_name" required value="{{$model->first_name}}" placeholder="First Name ...">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="last_name">Last Name</label>
                                        <input type="text" class="form-control" name="last_name" id="last_name" required value="{{$model->last_name}}" placeholder="Last Name ...">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" name="email" id="email" required value="{{$model->email}}" placeholder="Email ...">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="telephone">Telephone</label>
                                        <input type="tel" class="form-control" name="telephone" id="telephone" required value="{{$model->telephone}}" placeholder="Email ...">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="Position">Position</label>
                                        <input type="text" class="form-control" name="position" id="Position" value="{{$model->position}}"  placeholder="position">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="side">Company</label>
                                        <input type="text" class="form-control" name="side" id="side" value="{{$model->side}}"  placeholder="side">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="seat_number">Seat Number</label>
                                        <input type="text" class="form-control" name="seat_number" id="seat_number" value="{{$model->seat_number}}"  placeholder="Seat Number">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="is_attended">Attended</label>
                                        <select name="is_attended" id="is_attended"  class="form-control selectpicker"  required>
                                            <option value="0" @if($model->is_attended == 0) selected @endif >No</option>
                                            <option value="1" @if($model->is_attended == 1) selected @endif >Yes</option>
                                        </select>
                                    </div>


                                    <div class="form-group col-md-12">
                                        <label for="message">Message</label>
                                        <input type="text" class="form-control" name="message" id="message" value="{{$model->message}}"  placeholder="Message">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary float-right">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')

@endpush

resources/views/client/index.blade.php
@extends('layouts.app', ['activePage' => 'Registered-people-management', 'titlePage' => __('Registered People Management')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{$message}}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Registered People</h4>
                            <p class="card-category"> Here you can manage Data </p>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table class="table" id="main-table">
                                    <thead class="text-primary">
                                    <tr>
{{--                                        <th>ID</th>--}}
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Email</th>
                                        <th>Telephone</th>
                                        <th>Position</th>
                                        <th>Company</th>
                                        <th>Seat Number</th>
                                        <th>Message</th>
                                        <th>Attended</th>
                                        <th>Registered at</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        var table;
        $(function () {
            table = $('#main-table').DataTable({
                fixedHeader:true,
                processing: true,
                serverSide: true,
                colReorder: true,
                // scrollX: true,
                lengthMenu : [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                ajax: '{!! route('clients.index') !!}',
                dom: 'QBlfrtip',
                buttons: [
                    'csv',
                ],
                columns: [
                    {"data": "first_name"},
                    {"data": "last_name"},
                    {"data": "email"},
                    {"data": "telephone"},
                    {"data": "position"},
                    {"data": "side"},
                    {"data": "seat_number"},
                    {"data": "message"},
                    {"data": "is_attended" , "render" : function (data){
                            if(data === 0)
                                return "No";
                            if(data === 1)
                                return "Yes";
                            return "--"
                        }},

                    {"data": "created_at"},

                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            });
            table.on('click', '.delete', function () {
                $tr = $(this).closest('tr');
                if ($($tr).hasClass('child')) {
                    $tr = $tr.prev('.parent')
                }
                var data = table.row($tr).data();
                deleteOpr(data.id, `admin/clients/` + data.id, table);
            });
        });
    </script>
@endpush